''' This module contains helper model for finding & retrieving user '''

from sqlalchemy_init import db_obj  #import the sqlalchemy object

class UserModel(db_obj.Model):  #Extend the sqlalchemy object
    #Tell sqlalchemy where the models will be stored i.e. table & columns
    __tablename__ = 'users_table'

    #The only 3 columns of the user model that sqlalchemy will work with
    id = db_obj.Column(db_obj.Integer, primary_key=True, unique=True)
    username = db_obj.Column(db_obj.String(80))  #Character length
    password = db_obj.Column(db_obj.String(80))  #These must match the model item in __init__

    #The id is auto generated by the DB engine and sqlalchemy inserts that into the model obj
    def __init__(self, username, password):
        self.username = username
        self.password = password

    @classmethod
    def find_by_username(cls, username):
        ''' class method for finding a user by username '''
        return cls.query.filter_by(username=username).first()

    @classmethod
    def find_by_id(cls, id):
        ''' class method for finding a user by id '''
        return cls.query.filter_by(id=id).first()

    def save_user(self):
        db_obj.session.add(self)
        db_obj.session.commit()
