# create your drupal and postgres config here, based off the last assignment
version: '2'

services:
    drupal-server:
        build: . # build from a specific location
        image: custom-drupal # will name the built image this.
        ports:
            - 8080:80
        volumes:
            # See docker-compose docs for long syntax
            - drupal_modules:/var/www/html/modules
            - drupal_profiles:/var/www/html/profiles
            - drupal_themes:/var/www/html/themes
            - drupal_sites:/var/www/html/sites

    drupal-postgres-db:
        image: postgres:12.1
        environment:
            POSTGRES_DB: drupal
            POSTGRES_USER: root
            POSTGRES_PASSWORD: Password#1
        volumes:
            - drupal_postgres_db:/var/lib/postgresql/data

# Named volumes
volumes:
    drupal_modules:
    drupal_profiles:
    drupal_themes:
    drupal_sites:
    drupal_postgres_db:
